CREATE DATABASE DBKHACHSAN
GO
USE	DBKHACHSAN
GO
CREATE TABLE ROLES
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDR PRIMARY KEY (ID)
)
GO
CREATE TABLE NATIONALITY
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDNT PRIMARY KEY (ID)
)
GO
CREATE TABLE USERS
(
ID INT IDENTITY(1,1) NOT NULL,
USERNAME NVARCHAR(255) NOT NULL,
PASSWORD NVARCHAR(255) NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDUSER PRIMARY KEY (ID),
)
GO
CREATE TABLE CUSTOMER
(
ID INT IDENTITY(1,1) NOT NULL,
ID_USER INT NULL,
FULLNAME NVARCHAR(255) NOT NULL,
EMAIL NVARCHAR(255) NULL,
CITIZEN_ID_CODE NVARCHAR(12) NULL,
GENDER NVARCHAR(5) NULL,
DATE_OF_BIRTH DATETIME NULL,
PHONE_NUMBER NVARCHAR(12) NULL,
ADDRESS NVARCHAR(255) NULL,
IMG NVARCHAR(255) NULL,
ID_NATIONALITY INT NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDCT PRIMARY KEY (ID),
CONSTRAINT FK_ID_USER1 FOREIGN KEY (ID_USER) REFERENCES USERS,
CONSTRAINT FK_ID_NATIONALITY FOREIGN KEY (ID_NATIONALITY) REFERENCES NATIONALITY
)
GO
CREATE TABLE PERSONNEL
(
ID INT IDENTITY(1,1) NOT NULL,
ID_USER INT NOT NULL,
FULLNAME NVARCHAR(255) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL,
GENDER NVARCHAR(5) NOT NULL,
CITIZEN_ID_CODE NVARCHAR(12) NULL,
DATE_OF_BIRTH DATETIME NOT NULL,
PHONE_NUMBER NVARCHAR(12) NOT NULL,
ADDRESS NVARCHAR(MAX) NULL,
ID_NATIONALITY INT NOT NULL,
IMG NVARCHAR(MAX) NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDST PRIMARY KEY (ID),
CONSTRAINT FK_ID_USER2 FOREIGN KEY (ID_USER) REFERENCES USERS,
CONSTRAINT FK_ID_NATIONALITY2 FOREIGN KEY (ID_NATIONALITY) REFERENCES NATIONALITY
)
GO
CREATE TABLE AUTHORITY
(
ID INT IDENTITY(1,1) NOT NULL,
ID_ROLES INT NOT NULL,
ID_USER INT NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDAU PRIMARY KEY (ID),
CONSTRAINT FK_ID_ROLES2 FOREIGN KEY (ID_ROLES) REFERENCES ROLES,
CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS
)
CREATE TABLE NUMBER_OF_FLOORS
(
ID INT IDENTITY(1,1) NOT NULL,
NUMBER_OF_FLOORS INT NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDN PRIMARY KEY (ID)
)
GO
CREATE TABLE KIND_OF_ROOM
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
NOTE NVARCHAR(255) NULL,
PRICES FLOAT NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_KIND_OF_ROOM PRIMARY KEY (ID),
)

GO
CREATE TABLE ROOMS
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NULL,
ID_NUMBER_OF_FLOORS INT NOT NULL,
ID_KIND_OF_ROOM INT NOT NULL,
NOTE NVARCHAR(255) NULL,
IMG NVARCHAR(255) NULL,
PRICES FLOAT NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDROOM PRIMARY KEY (ID),
CONSTRAINT FK_ID_NUMBER_OF_FLOORS FOREIGN KEY (ID_NUMBER_OF_FLOORS) REFERENCES NUMBER_OF_FLOORS,
CONSTRAINT FK_ID_KIND_OF_ROOM FOREIGN KEY (ID_KIND_OF_ROOM) REFERENCES KIND_OF_ROOM

)
GO
CREATE TABLE FACILITIES
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_FACILITIES PRIMARY KEY (ID)
)
GO
CREATE TABLE FACILITIES_DETAILS
(
ID INT IDENTITY(1,1) NOT NULL,
ID_FACILITIES INT NOT NULL,
ID_ROOMS INT NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDFACILITIESDETAILS PRIMARY KEY (ID),
CONSTRAINT FK_ID_FACILITIES FOREIGN KEY (ID_FACILITIES) REFERENCES FACILITIES,
CONSTRAINT FK_ID_ROOMS FOREIGN KEY (ID_ROOMS) REFERENCES ROOMS
)
GO 
CREATE TABLE RENTAL_TYPES
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_RENTAL_TYPES PRIMARY KEY (ID)
)
GO
CREATE TABLE PAYMENT_TYPE
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_PAYMENT_TYPE PRIMARY KEY (ID),
)
GO
CREATE TABLE BILLS
(
ID INT IDENTITY(1,1) NOT NULL,
ID_CUSTOMER INT NOT NULL,
ID_PERSONNEL INT NOT NULL,
ID_PAYMENT_TYPE INT NOT NULL,
HIRE_DATE DATETIME NOT NULL,
CHECK_OUT_DAY DATETIME NULL,
NUMBER_OF_ROOM INT NULL,
NUMBER_OF_PEOPLE INT NULL,
DATE_OF_PAYMENT DATETIME NULL,
TOTAL_CASH FLOAT NULL, 
STATUS INT NOT NULL

CONSTRAINT PK_ID_BILLS PRIMARY KEY (ID),
CONSTRAINT FK_ID_CUSTOMER FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER,
CONSTRAINT FK_ID_PERSONNEL FOREIGN KEY (ID_PERSONNEL) REFERENCES PERSONNEL,
CONSTRAINT FK_ID_PAYMENT_TYPE FOREIGN KEY (ID_PAYMENT_TYPE) REFERENCES PAYMENT_TYPE
)
GO
CREATE TABLE DETAILS_INVOICE
(
ID INT IDENTITY(1,1) NOT NULL,
ID_BILL INT NOT NULL,
ID_ROOMS INT NOT NULL,
NUMBER_OF_DAYS_OF_RENT DATETIME NULL,
NUMBER_OF_HOURS_TO_RENT NVARCHAR(10) NULL,
NUMBER_OF_PEOPLE INT NULL,
TOTAL_CASH FLOAT NULL, 
STATUS INT NOT NULL

CONSTRAINT PK_ID_DETAILS_INVOICE PRIMARY KEY (ID),
CONSTRAINT FK_ID_BILL3 FOREIGN KEY (ID_BILL) REFERENCES BILLS,
CONSTRAINT FK_ID_ROOMS_3 FOREIGN KEY (ID_ROOMS) REFERENCES ROOMS,
)
GO
CREATE TABLE DETAILS_OF_RENTAL_TYPES
(
ID INT IDENTITY(1,1) NOT NULL,
ID_RENTAL_TYPES INT NOT NULL,
ID_DETAILS_INVOICE INT NOT NULL,
DAY_IN DATETIME NULL,
DAY_OUT DATETIME NULL,
TIME_IN NVARCHAR(12) NULL,
TIME_OUT NVARCHAR(12) NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_DETAILS_OF_RENTAL_TYPES PRIMARY KEY (ID),
CONSTRAINT FK_ID_RENTAL_TYPES FOREIGN KEY (ID_RENTAL_TYPES) REFERENCES RENTAL_TYPES,
CONSTRAINT ID_DETAILS_INVOICE2 FOREIGN KEY (ID_DETAILS_INVOICE) REFERENCES DETAILS_INVOICE
)
GO
CREATE TABLE BOOKING_TYPE
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_BOOKING_TYPE PRIMARY KEY (ID)
)
GO
CREATE TABLE BOOKING
(
ID INT IDENTITY(1,1) NOT NULL,
ID_BILL INT NOT NULL,
ID_BOOKING_TYPE INT NOT NULL,
DATE_OF_HIRE DATETIME NOT NULL,
TIME_IN NVARCHAR(15) NULL,
TIME_OUT NVARCHAR(15) NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDBOOKING PRIMARY KEY (ID),
CONSTRAINT FK_ID_BILL2 FOREIGN KEY (ID_BILL) REFERENCES BILLS,
CONSTRAINT FK_ID_BOOKING_TYPE FOREIGN KEY (ID_BOOKING_TYPE) REFERENCES BOOKING_TYPE
)
GO
CREATE TABLE SERVICE_TYPE
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
NOTE NVARCHAR(255) NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_SERVICE_TYPE PRIMARY KEY (ID),
)
GO
CREATE TABLE SERVICESS
(
ID INT IDENTITY(1,1) NOT NULL,
NAME NVARCHAR(255) NOT NULL,
ID_SERVICE_TYPE INT NOT NULL,
PRICES FLOAT NOT NULL,
NOTE NVARCHAR(255) NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_SERVICESS PRIMARY KEY (ID),
CONSTRAINT FK_ID_SERVICE_TYPE FOREIGN KEY (ID_SERVICE_TYPE) REFERENCES SERVICE_TYPE
)
GO
CREATE TABLE SERVICE_DETAILS
(
ID INT IDENTITY(1,1) NOT NULL,
ID_SERVICE INT NOT NULL,
ID_DETAILS_INVOICE INT NOT NULL,
QUANTITY INT NOT NULL,
TOTAL_CASH FLOAT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_SERVICE_DETAILS PRIMARY KEY (ID),
CONSTRAINT FK_ID_SERVICE FOREIGN KEY (ID_SERVICE) REFERENCES SERVICESS,
CONSTRAINT FK_ID_DETAILS_INVOICE FOREIGN KEY (ID_DETAILS_INVOICE) REFERENCES DETAILS_INVOICE
)
GO
CREATE TABLE SERVICE_AVAILABLE
(
ID INT IDENTITY(1,1) NOT NULL,
ID_SERVICE INT NOT NULL,
ID_ROOMS INT NOT NULL,
QUANTITY INT NOT NULL,
PRICES FLOAT NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_ID_SERVICE_AVAILABLE PRIMARY KEY (ID),
CONSTRAINT FK_ID_SERVICES FOREIGN KEY (ID_SERVICE) REFERENCES SERVICESS,
CONSTRAINT FK_ID_ROOMS4 FOREIGN KEY (ID_ROOMS) REFERENCES ROOMS
)


