CREATE DATABASE DBKHACHSAN
GO

USE DBKHACHSAN
GO

-------------
CREATE TABLE ROLES
(
ID INT IDENTITY(1,1) NOT NULL,
ROLES NVARCHAR(6) NOT NULL

CONSTRAINT PK_IDR PRIMARY KEY (ID),
)
GO

-------------------
CREATE TABLE USERS
(
ID INT IDENTITY(1,1) NOT NULL,
USERNAME NVARCHAR(30) NOT NULL,
PASSWORD NVARCHAR(30) NOT NULL,
STATUS INT NOT NULL

CONSTRAINT PK_IDUSER PRIMARY KEY (ID),
)
GO

--------------------
CREATE TABLE AUTHORITY
(
ID INT IDENTITY(1,1) NOT NULL,
ID_ROLES INT NOT NULL,
ID_USER INT NOT NULL,
CONSTRAINT PK_IDAU PRIMARY KEY (ID),
CONSTRAINT FK_ID_ROLES FOREIGN KEY (ID_ROLES) REFERENCES ROLES,
CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS,
)
GO

---------------------
CREATE TABLE CUSTOMER
(
CUSTOMER_ID INT IDENTITY(1,1) NOT NULL,
USERS_ID INT NOT NULL,
FULLNAME NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL,
GENDER NVARCHAR(3) NOT NULL,
DATE_OF_BIRTH DATETIME NOT NULL,
PHONE_NUMBER NVARCHAR(12) NOT NULL,
ADDRESSS NVARCHAR(MAX) NULL,
IMG NVARCHAR(MAX) NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_IDCT PRIMARY KEY (CUSTOMER_ID),
CONSTRAINT FK_ID_USER1 FOREIGN KEY (USERS_ID) REFERENCES USERS
)
GO

----------------------
CREATE TABLE EMPLOYEES
(
EMPLOYEES_ID INT IDENTITY(1,1) NOT NULL,
USERS_ID INT NOT NULL,
FULLNAME NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL,
GENDER NVARCHAR(3) NOT NULL,
DATE_OF_BIRTH DATETIME NOT NULL,
PHONE_NUMBER NVARCHAR(12) NOT NULL,
ADDRESSS NVARCHAR(MAX) NULL,
IMG NVARCHAR(MAX) NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_IDST PRIMARY KEY (EMPLOYEES_ID),
CONSTRAINT FK_ID_USER2 FOREIGN KEY (USERS_ID) REFERENCES USERS
)
GO

--------------------------
CREATE TABLE NUMBER_OF_FLOORS
(
NOF_ID INT IDENTITY(1,1) NOT NULL,
NUMBER_OF_FLOORS INT NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_IDN PRIMARY KEY (NOF_ID),
)
GO

-------------------------
CREATE TABLE KIND_OF_ROOM
(
KOR_ID INT IDENTITY(1,1) NOT NULL,
ROOM_TYPE_NAME NVARCHAR(30) NOT NULL,
NOTE NVARCHAR(30) NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_KIND_OF_ROOM PRIMARY KEY (KOR_ID),
)

GO

---------------------------
CREATE TABLE ROOMS
(
ROOMS_ID INT IDENTITY(1,1) NOT NULL,
NUMBER_OF_FLOORS_ID INT NOT NULL,
KIND_OF_ROOM_ID INT NOT NULL,
NOTE NVARCHAR(50) NULL,
IMG NVARCHAR(MAX) NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_IDROOM PRIMARY KEY (ROOMS_ID),
CONSTRAINT FK_ID_NUMBER_OF_FLOORS FOREIGN KEY (NUMBER_OF_FLOORS_ID) REFERENCES NUMBER_OF_FLOORS,
CONSTRAINT FK_ID_KIND_OF_ROOM FOREIGN KEY (KIND_OF_ROOM_ID) REFERENCES KIND_OF_ROOM

)
GO

--------------------------
CREATE TABLE FACILITIES
(
FACILITIES_ID INT IDENTITY(1,1) NOT NULL,
FACILITIES_NAME NVARCHAR(30) NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_FACILITIES PRIMARY KEY (FACILITIES_ID)
)
GO

----------------------------
CREATE TABLE FACILITIES_DETAILS
(
FADE_ID INT IDENTITY(1,1) NOT NULL,
FACILITIES_ID INT NOT NULL,
ROOMS_ID INT NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_IDFACILITIESDETAILS PRIMARY KEY (FADE_ID),
CONSTRAINT FK_ID_FACILITIES FOREIGN KEY (FACILITIES_ID) REFERENCES FACILITIES,
CONSTRAINT FK_ID_ROOMS FOREIGN KEY (ROOMS_ID) REFERENCES ROOMS
)
GO 

----------------------------
CREATE TABLE RENTAL_TYPES
(
RETY_ID INT IDENTITY(1,1) NOT NULL,
RENTAL_TYPE NVARCHAR(30) NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_RENTAL_TYPES PRIMARY KEY (RETY_ID),
)
GO

-----------------------
CREATE TABLE PAYMENT_TYPE
(
PAYTY_ID INT IDENTITY(1,1) NOT NULL,
PAYMENT_TYPE NVARCHAR(15) NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_PAYMENT_TYPE PRIMARY KEY (PAYTY_ID),
)
GO

-------------------------
CREATE TABLE BILLS
(
BILLS_ID INT IDENTITY(1,1) NOT NULL,
CUSTOMERS_ID INT NOT NULL,
EMPLOYEES_ID INT NOT NULL,
PAYMENT_TYPE_ID INT NOT NULL,
HIRE_DATE DATETIME NOT NULL,
CHECK_OUT_DAY DATETIME NOT NULL,
NUMBER_OF_PEOPLE INT NOT NULL,
DATE_OF_PAYMENT DATETIME NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_BILLS PRIMARY KEY (BILLS_ID),
CONSTRAINT FK_ID_CUSTOMER FOREIGN KEY (CUSTOMERS_ID) REFERENCES CUSTOMER,
CONSTRAINT FK_ID_EMPLOYEES FOREIGN KEY (EMPLOYEES_ID) REFERENCES EMPLOYEES,
CONSTRAINT FK_ID_PAYMENT_TYPE FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES PAYMENT_TYPE,
)
GO

-----------------------------
CREATE TABLE BILL_DETAILS
(
BIDE_ID INT IDENTITY(1,1) NOT NULL,
BILLS_ID INT NOT NULL,
ROOMS_ID INT NOT NULL,
RENTAL_TYPE_ID INT NOT NULL,
NUMBER_OF_DAYS_OF_RENT DATETIME NULL,
NUMBER_OF_HOURS_TO_RENT NVARCHAR(10) NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_BILL_DETAILS PRIMARY KEY (BIDE_ID),
CONSTRAINT FK_ID_BILL3 FOREIGN KEY (BILLS_ID) REFERENCES BILLS,
CONSTRAINT FK_ID_ROOMS_3 FOREIGN KEY (ROOMS_ID) REFERENCES ROOMS,
CONSTRAINT FK_ID_RENTAL_TYPES FOREIGN KEY (RENTAL_TYPE_ID) REFERENCES RENTAL_TYPES,
)
GO

--------------------------------
CREATE TABLE BOOKING_TYPE
(
BOOTY_ID INT IDENTITY(1,1) NOT NULL,
BOOKING_TYPE NVARCHAR(30) NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_BOOKING_TYPE PRIMARY KEY (BOOTY_ID)
)
GO

--------------------------------
CREATE TABLE BOOKING
(
BOOKING_ID INT IDENTITY(1,1) NOT NULL,
BILLS_ID INT NOT NULL,
BOOKING_TYPE_ID INT NOT NULL,
DATE_OF_HIRE DATETIME NOT NULL,
TIME_IN NVARCHAR(15) NULL,
TIME_OUT NVARCHAR(15) NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_IDBOOKING PRIMARY KEY (BOOKING_ID),
CONSTRAINT FK_ID_BILL2 FOREIGN KEY (BILLS_ID) REFERENCES BILLS,
CONSTRAINT FK_ID_BOOKING_TYPE FOREIGN KEY (BOOKING_TYPE_ID) REFERENCES BOOKING_TYPE
)
GO

--------------------------------
CREATE TABLE SERVICE_TYPE
(
SERTY_ID INT IDENTITY(1,1) NOT NULL,
SERVICES_TYPE NVARCHAR(20) NOT NULL,
NOTE NVARCHAR(30) NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_SERVICE_TYPE PRIMARY KEY (SERTY_ID),
)
GO

------------------------
CREATE TABLE SERVICESS
(
SER_ID INT IDENTITY(1,1) NOT NULL,
SERVICES_NAME NVARCHAR(20) NOT NULL,
SERVICE_TYPE_ID INT NOT NULL,
PRICES FLOAT NOT NULL,
NOTE NVARCHAR(30) NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_SERVICESS PRIMARY KEY (SER_ID),
CONSTRAINT FK_ID_SERVICE_TYPE FOREIGN KEY (SERVICE_TYPE_ID) REFERENCES SERVICE_TYPE
)
GO

------------------------
CREATE TABLE SERVICE_DETAILS
(
SERDE_ID INT IDENTITY(1,1) NOT NULL,
SERVICE_ID INT NOT NULL,
BILL_DETAILS_ID INT NOT NULL,
QUANTITY INT NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_SERVICE_DETAILS PRIMARY KEY (SERDE_ID),
CONSTRAINT FK_ID_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICESS,
CONSTRAINT FK_ID_BILL_DETAILS FOREIGN KEY (BILL_DETAILS_ID) REFERENCES BILL_DETAILS
)
GO

-----------------------------
CREATE TABLE SERVICE_AVAILABLE
(
SERAV_ID INT IDENTITY(1,1) NOT NULL,
SERVICE_ID INT NOT NULL,
BILL_DETAILS_ID INT NOT NULL,
QUANTITY INT NOT NULL,
TOTAL_CASH FLOAT NOT NULL,
STATUSS INT NOT NULL

CONSTRAINT PK_ID_SERVICE_AVAILABLE PRIMARY KEY (SERAV_ID),
CONSTRAINT FK_ID_SERVICES FOREIGN KEY (SERVICE_ID) REFERENCES SERVICESS,
CONSTRAINT FK_ID_BILLDETAILS FOREIGN KEY (BILL_DETAILS_ID) REFERENCES BILL_DETAILS
)
GO