const routes = {
    home: '/',
    loginAdmin: '/admin/login',
    homeAdmin: '/admin',
    historyAdmin: '/admin/history',
    roomAdmin: '/admin/room-check/:information',
    personnelManage: '/admin/personnel-manage',
    serviceManage: '/admin/service-manage',
    handOver: '/admin/hand-over',
    handOverManage: '/admin/hand-over-manage',
    customerManage: '/admin/customer-manage',
    numberOfFloorManage: '/admin/number-floor-manage',
    nationality: '/admin/nationality',
    searchRoom: '/room/search',
    room: '/room/detail',
    rentalTypeManage: '/admin/rental-type-manage',
    facilityManage: '/admin/facility-manage',
    login: '/login',
    signup: '/signup',
    notfound: '/*',
};
export default routes;
